export const AI_ACT_BASE = 'AI Act (Verordening 2024/1689)';
export const AVG_BASE = 'AVG (Verordening 2016/679)';
export const SIVON_BASE = 'SIVON Toetsingskader 2026';

export const obligations = [
  // --- Verboden (Art. 5) ---
  {
    id: 'v1',
    basis: AI_ACT_BASE,
    artikel: 'Art. 5 lid 1(a)',
    verplichting: 'Verbod op subliminale manipulatie — onmiddellijk staken van de praktijk',
    voor: ['school', 'leverancier'],
    risico: 'verboden',
    prioriteit: 'Hoogst',
    deadline: 'Direct',
    verantwoordelijke: 'Directie / CvB',
  },
  {
    id: 'v2',
    basis: AI_ACT_BASE,
    artikel: 'Art. 5 lid 1(c)',
    verplichting: 'Verbod op social scoring door overheid — onmiddellijk staken',
    voor: ['school', 'leverancier'],
    risico: 'verboden',
    prioriteit: 'Hoogst',
    deadline: 'Direct',
    verantwoordelijke: 'Directie / CvB',
  },
  {
    id: 'v3',
    basis: AI_ACT_BASE,
    artikel: 'Art. 5 lid 1(d)',
    verplichting: 'Verbod op realtime biometrische identificatie in openbare ruimte (uitgezonderd)',
    voor: ['school', 'leverancier'],
    risico: 'verboden',
    prioriteit: 'Hoogst',
    deadline: 'Direct',
    verantwoordelijke: 'Directie / CvB',
  },
  {
    id: 'v4',
    basis: AI_ACT_BASE,
    artikel: 'Art. 5 lid 1(f)',
    verplichting: 'Verbod op emotieherkenning op werkplek en in onderwijs',
    voor: ['school', 'leverancier'],
    risico: 'verboden',
    prioriteit: 'Hoogst',
    deadline: 'Direct',
    verantwoordelijke: 'Functionaris Gegevensbescherming (FG)',
  },
  {
    id: 'v5',
    basis: AI_ACT_BASE,
    artikel: 'Art. 5 lid 1(b)',
    verplichting: 'Verbod op uitbuiten van kwetsbaarheden van leerlingen (leeftijd/beperking)',
    voor: ['school', 'leverancier'],
    risico: 'verboden',
    prioriteit: 'Hoogst',
    deadline: 'Direct',
    verantwoordelijke: 'Privacy Officer (PO) / FG',
  },

  // --- Hoog risico (Art. 6-7) ---
  {
    id: 'hr1',
    basis: AI_ACT_BASE,
    artikel: 'Art. 9',
    verplichting: 'Risicobeheersysteem opzetten voor de gehele levenscyclus',
    voor: ['school', 'leverancier'],
    risico: 'hoog_risico',
    prioriteit: 'Hoog',
    deadline: '1 maand',
    verantwoordelijke: 'AI Officer / Projectleider',
  },
  {
    id: 'hr2',
    basis: AI_ACT_BASE,
    artikel: 'Art. 10',
    verplichting: 'Datakwaliteits- en datagovernanceprocedures implementeren (training, validatie, test)',
    voor: ['school', 'leverancier'],
    risico: 'hoog_risico',
    prioriteit: 'Hoog',
    deadline: '2 maanden',
    verantwoordelijke: 'Data Owner / Functionaris Gegevensbescherming (FG)',
  },
  {
    id: 'hr3',
    basis: AI_ACT_BASE,
    artikel: 'Art. 11',
    verplichting: 'Technische documentatie opstellen (doel, ontwerp, prestatie, risico\'s)',
    voor: ['school', 'leverancier'],
    risico: 'hoog_risico',
    prioriteit: 'Hoog',
    deadline: '1 maand',
    verantwoordelijke: 'Ontwikkelteam / AI Officer',
  },
  {
    id: 'hr4',
    basis: AI_ACT_BASE,
    artikel: 'Art. 12',
    verplichting: 'Logging- en registratieverplichting (traceerbaarheid besluiten)',
    voor: ['school', 'leverancier'],
    risico: 'hoog_risico',
    prioriteit: 'Midden',
    deadline: '3 maanden',
    verantwoordelijke: 'IT / Informatiemanager',
  },
  {
    id: 'hr5',
    basis: AI_ACT_BASE,
    artikel: 'Art. 13',
    verplichting: 'Transparantie en informatieplicht richting gebruikers (docenten/leerlingen)',
    voor: ['school', 'leverancier'],
    risico: 'hoog_risico',
    prioriteit: 'Hoog',
    deadline: '1 maand',
    verantwoordelijke: 'Communicatie / PO',
  },
  {
    id: 'hr6',
    basis: AI_ACT_BASE,
    artikel: 'Art. 14',
    verplichting: 'Menselijk toezicht inrichten (HITL/HOTL/HOC)',
    voor: ['school', 'leverancier'],
    risico: 'hoog_risico',
    prioriteit: 'Hoog',
    deadline: '1 maand',
    verantwoordelijke: 'Onderwijsmanager / Teamleider',
  },
  {
    id: 'hr7',
    basis: AI_ACT_BASE,
    artikel: 'Art. 15',
    verplichting: 'Nauwkeurigheid, robuustheid en cybersecurity waarborgen',
    voor: ['school', 'leverancier'],
    risico: 'hoog_risico',
    prioriteit: 'Midden',
    deadline: '3 maanden',
    verantwoordelijke: 'IT / Security Officer',
  },
  {
    id: 'hr8',
    basis: AI_ACT_BASE,
    artikel: 'Art. 16-17',
    verplichting: 'CE-markering en conformiteitsbeoordeling (leverancier)',
    voor: ['leverancier'],
    risico: 'hoog_risico',
    prioriteit: 'Hoog',
    deadline: 'Voor ingebruikname',
    verantwoordelijke: 'Kwaliteitsmanager / Ontwikkelteam',
  },
  {
    id: 'hr9',
    basis: AI_ACT_BASE,
    artikel: 'Art. 26',
    verplichting: 'Verplichtingen van gebruiksverantwoordelijken (school: toezicht, logging, menselijk toezicht)',
    voor: ['school'],
    risico: 'hoog_risico',
    prioriteit: 'Hoog',
    deadline: '1 maand',
    verantwoordelijke: 'Directie / AI Officer',
  },

  // --- AVG specifiek voor Hoog risico ---
  {
    id: 'avg1',
    basis: AVG_BASE,
    artikel: 'Art. 5',
    verplichting: 'Rechtmatigheid, behoorlijkheid en transparantie van gegevensverwerking',
    voor: ['school', 'leverancier'],
    risico: 'hoog_risico',
    prioriteit: 'Hoog',
    deadline: 'Doorlopend',
    verantwoordelijke: 'FG / PO',
  },
  {
    id: 'avg2',
    basis: AVG_BASE,
    artikel: 'Art. 35',
    verplichting: 'Data Protection Impact Assessment (DPIA) uitvoeren',
    voor: ['school', 'leverancier'],
    risico: 'hoog_risico',
    prioriteit: 'Hoog',
    deadline: 'Voor ingebruikname',
    verantwoordelijke: 'FG / PO',
  },
  {
    id: 'avg3',
    basis: AVG_BASE,
    artikel: 'Art. 22',
    verplichting: 'Recht op niet onderworpen te worden aan geautomatiseerde besluitvorming',
    voor: ['school', 'leverancier'],
    risico: 'hoog_risico',
    prioriteit: 'Hoog',
    deadline: 'Voor ingebruikname',
    verantwoordelijke: 'PO / FG',
  },
  {
    id: 'avg4',
    basis: AVG_BASE,
    artikel: 'Art. 13-14',
    verplichting: 'Informatieplicht betrokkenen (leerlingen/ouders) over verwerking',
    voor: ['school', 'leverancier'],
    risico: 'hoog_risico',
    prioriteit: 'Hoog',
    deadline: '1 maand',
    verantwoordelijke: 'PO / Communicatie',
  },

  // --- Beperkt / Minimaal risico (niet-hoog-risico AI) ---
  {
    id: 'b1',
    basis: AI_ACT_BASE,
    artikel: 'Art. 50 lid 1',
    verplichting: 'Transparantieplicht: gebruikers informeren dat ze met AI interageren',
    voor: ['school', 'leverancier'],
    risico: 'beperkt',
    prioriteit: 'Midden',
    deadline: '2 maanden',
    verantwoordelijke: 'Communicatie / PO',
  },
  {
    id: 'b2',
    basis: AI_ACT_BASE,
    artikel: 'Art. 50 lid 2',
    verplichting: 'Synthetische content markeren als AI-gegenereerd (deepfakes/tekst)',
    voor: ['school', 'leverancier'],
    risico: 'beperkt',
    prioriteit: 'Midden',
    deadline: '2 maanden',
    verantwoordelijke: 'Communicatie',
  },
  {
    id: 'b3',
    basis: AVG_BASE,
    artikel: 'Art. 5',
    verplichting: 'Basis beginselen gegevensbescherming borgen (doelbinding, minimale data)',
    voor: ['school', 'leverancier'],
    risico: 'beperkt',
    prioriteit: 'Laag',
    deadline: '6 maanden',
    verantwoordelijke: 'PO / FG',
  },
  {
    id: 'b4',
    basis: SIVON_BASE,
    artikel: '2026-001',
    verplichting: 'SIVON-richtlijn voor laag-risico AI: informatieplicht naar ouders',
    voor: ['school'],
    risico: 'beperkt',
    prioriteit: 'Midden',
    deadline: '3 maanden',
    verantwoordelijke: 'PO / Communicatie',
  },

  // --- Geen AI ---
  {
    id: 'g1',
    basis: '—',
    artikel: '—',
    verplichting: 'Geen bijzondere verplichtingen onder AI Act; reguliere monitoring volstaat',
    voor: ['school', 'leverancier'],
    risico: 'geen_ai',
    prioriteit: 'Laag',
    deadline: 'Jaarlijks',
    verantwoordelijke: 'Informatiemanager',
  },
  {
    id: 'g2',
    basis: AVG_BASE,
    artikel: 'Art. 32',
    verplichting: 'Basis beveiligingsmaatregelen (ondanks geen AI-classificatie)',
    voor: ['school', 'leverancier'],
    risico: 'geen_ai',
    prioriteit: 'Laag',
    deadline: 'Doorlopend',
    verantwoordelijke: 'IT / Security Officer',
  },

  // --- Overkoepelend / voor iedere AI ---
  {
    id: 'o1',
    basis: SIVON_BASE,
    artikel: '2026-xxx',
    verplichting: 'Melding bij SIVON-toetsingscommissie voor nieuwe AI-toepassingen',
    voor: ['school'],
    risico: 'hoog_risico',
    prioriteit: 'Midden',
    deadline: '1 maand na implementatie',
    verantwoordelijke: 'AI Officer',
  },
  {
    id: 'o2',
    basis: SIVON_BASE,
    artikel: '2026-xxx',
    verplichting: 'Raadpleeg medezeggenschapsraad bij invoering AI in onderwijs',
    voor: ['school'],
    risico: 'hoog_risico',
    prioriteit: 'Midden',
    deadline: 'Voor ingebruikname',
    verantwoordelijke: 'Directie / Bestuur',
  },
  {
    id: 'o3',
    basis: AI_ACT_BASE,
    artikel: 'Art. 69',
    verplichting: 'Registratie in EU-databank voor hoog-risico AI-systemen (leverancier)',
    voor: ['leverancier'],
    risico: 'hoog_risico',
    prioriteit: 'Midden',
    deadline: 'Voor ingebruikname',
    verantwoordelijke: 'Kwaliteitsmanager',
  },
];

export function getObligationsFor(riskLevel, role) {
  return obligations.filter(
    (o) => o.risico === riskLevel && o.voor.includes(role)
  );
}
